version: "3.8"
services:
  votezone:
    image: votezone:latest
    container_name: votezone_container
    depends_on:
      - votezone_primary_database
      - votezone_quartz_database
    build:
      context: .
    ports:
      - "8088:8088"
    environment:
      - MAIN_DATABASE_HOST=${MAIN_DATABASE_HOST}
      - MAIN_DATABASE_PORT=${MAIN_DATABASE_PORT}
      - QUARTZ_DATABASE_HOST=${QUARTZ_DATABASE_HOST}
      - QUARTZ_DATABASE_PORT=${QUARTZ_DATABASE_PORT}
    volumes:
      - votezone_logs:/app/logs

  votezone_primary_database:
    image: postgres:14.5-alpine
    container_name: votezone_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER_VOTEZONE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_VOTEZONE}
      POSTGRES_DB: ${POSTGRES_DB_VOTEZONE}
    volumes:
      - primary-db-data:/var/lib/postgresql/votezone

  votezone_quartz_database:
    image: postgres:14.5-alpine
    container_name: quartz_db_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER_QUARTZ}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_QUARTZ}
      POSTGRES_DB: ${POSTGRES_DB_QUARTZ}
    volumes:
      - quartz-db-data:/var/lib/postgresql/quartz

volumes:
  primary-db-data:
  quartz-db-data:
  votezone_logs:
